### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by zh-h** [isnowfy/snownlp#43]
```
 * Running on http://127.0.0.1:8001/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "weibo_sentiment/main.py", line 24, in <module>
    from weibo_sentiment import (
  File "/home/www/weibo_sentiment/weibo_sentiment/weibo_model.py", line 10, in <module>
    from snownlp import SnowNLP
  File "/usr/local/lib/python2.7/dist-packages/snownlp/__init__.py", line 5, in <module>
    from . import seg
  File "/usr/local/lib/python2.7/dist-packages/snownlp/seg/__init__.py", line 12, in <module>
    segger.load(data_path, True)
  File "/usr/local/lib/python2.7/dist-packages/snownlp/seg/seg.py", line 23, in load
    self.segger.load(fname, iszip)
  File "/usr/local/lib/python2.7/dist-packages/snownlp/seg/y09_2047.py", line 51, in load
    data = f.read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 313, in _read
    self._add_read_data( uncompress )
  File "/usr/lib/python2.7/gzip.py", line 331, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError
```
It is running on Aliyun ECS 1GB RAM.
```
File "/usr/local/lib/python2.7/dist-packages/snownlp/seg/y09_2047.py", line 51, in load
    data = f.read()
```
Change to readlines ?

**Comment by isnowfy** [comment]
分词应该不会占用太大，即使按你说的改成readlines最后解析完在内存中的model也会比较大，你可以看看是不是其他的应用已经占用了大部分的内存

**Comment by zh-h** [comment]
@isnowfy 我在本地上试了一下，占用超过1GB内存。

**Comment by isnowfy** [comment]
因为包含很多个模块，若干个模块加起来自然就大了，如果只需要单独的模块可以把其他的注释掉
